### ISSUE TITLE
Feature request: transaction hash in message/sync events

### ISSUE THREAD

**Issue by odesenfans** [aleph-im/aleph-indexer-framework#41]
The message/sync events returned by the Aleph smart contract indexer do not contain the transaction hash. CCNs typically use the transaction hash as primary key for some tables. I can use the indexer `id` field for now but having the transaction hash directly available would be cleaner.

**Comment by amalcaraz** [comment]
Duplicated
https://github.com/aleph-im/aleph-indexer-framework/issues/42
