### ISSUE TITLE
Problem: the event ID field contains the emitter address instead of the transaction hash

### ISSUE THREAD

**Issue by odesenfans** [aleph-im/aleph-indexer-framework#42]
Ex: in `ethereum_16698727_0x166fd4299364b21c7567e163d85d78d2fb2f8ad5_52`, `0x166fd4299364b21c7567e163d85d78d2fb2f8ad5` is the address that emitted the transaction and not the transaction hash.

**Comment by amalcaraz** [comment]
The main reason for having the contract address as part of the id is to optimize the fetching process.

The common ethereum rpc apis doesn't support neither fetching logs by id, nor transaction hash, but they support fetching by block height and contract account. Then there is always a local filtering using the log index which specify a unique index inside the block, but the network request is faster and the response is lighter.

https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_getlogs

Regardless, it could be useful to include the transaction hash as part of the log body

**Comment by amalcaraz** [comment]
In the framework side (fetcher & parser) the log model [already contains](https://github.com/aleph-im/aleph-indexer-framework/blob/main/packages/ethereum/src/types.ts#L44) block and transaction contextual information.

In the indexer side however, we are discarding all this information when we build out own event schema. I have included transaction hash as part of the MessageEvent and SyncEvent schemas on the aleph-indexer, take a look at the PR:

https://github.com/aleph-im/aleph-indexer-library/pull/12
