### ISSUE TITLE
Problem: string content in message event results in error

### ISSUE THREAD

**Issue by odesenfans** [aleph-im/aleph-indexer-framework#44]
Creating a message event with the Aleph message smart contract results in a query response error when fetching it from the indexer. We define a `STORE_IPFS` message type that takes an IPFS hash in the `msgcontent` field in string format, without quotation marks. This works and is used with the Tezos indexer ([example](https://better-call.dev/ghostnet/KT1SZsqvcLUqwWLZVrSfD8At5gB54jJXWqAc/operations)).

![Creating the event on etherscan](https://user-images.githubusercontent.com/8036060/226371614-c4295f97-8252-4fac-becc-bc6ce16f5f0e.png)

[The resulting transaction](https://etherscan.io/tx/0xd15a1052e0c69e4e2342881718fe457552cdaf4f05030f51b85f238af4fea994)

[The indexer query](https://multichain.api.aleph.cloud/?query=query%20(%24bc%3A%20Blockchain!)%20%7B%0A%20%20time%0A%0A%20%20%0A%20%20messageEvents(%0A%20%20%20%20blockchain%3A%20%24bc%0A%20%20)%20%7B%0A%20%20%20%20id%0A%20%20%20%20timestamp%0A%20%20%20%20address%0A%20%20%20%20height%0A%20%20%20%20type%0A%20%20%20%20content%0A%20%20%7D%0A%7D&variables=%7B%22bc%22%3A%20%22ethereum%22%7D)

![Indexer response](https://user-images.githubusercontent.com/8036060/226372382-51ba8180-7f67-49d2-82f5-0e2108327f92.png)

**Comment by amalcaraz** [comment]
For not breaking the current Event schema in case that the event content is not a valid stringified JSON. A plain object will be returned instead. It will contain the original non parsed `value`.

Take a look at: https://github.com/aleph-im/aleph-indexer-library/commit/7420083b80b85d7e5cff3530cb074cfdf68b0ed6
